"""Data models package."""

from .chess_models import (
    MoveClassification,
    PatternType,
    BlunderType,
    PositionEvaluation,
    AlternativeMove,
    TacticalPattern,
    MoveAnalysis,
    OpeningInfo,
    CriticalMoment,
    GamePhaseStats,
    PlayerAnalysis,
    GameAnalysis,
    PatternSummary,
    WeaknessAnalysis,
    EngineConfig,
    AnalysisRequest,
    AnalysisResponse,
)

from .chess_com import (
    PlayerProfile,
    PlayerStats,
    GamePlayer,
    ChessGame,
    MonthlyGames,
    PlayerArchives,
    ParsedGame,
)

__all__ = [
    "MoveClassification",
    "PatternType",
    "BlunderType",
    "PositionEvaluation",
    "AlternativeMove",
    "TacticalPattern",
    "MoveAnalysis",
    "OpeningInfo",
    "CriticalMoment",
    "GamePhaseStats",
    "PlayerAnalysis",
    "GameAnalysis",
    "PatternSummary",
    "WeaknessAnalysis",
    "EngineConfig",
    "AnalysisRequest",
    "AnalysisResponse",
    "PlayerProfile",
    "PlayerStats",
    "GamePlayer",
    "ChessGame",
    "MonthlyGames",
    "PlayerArchives",
    "ParsedGame",
]
